Tichau/FileConverter

Application/FileConverter/Application.xaml.cs, Application/FileConverter/ConversionJobs/ConversionJob_FFMPEG.cs, Application/FileConverter/FileConverter.csproj, Application/FileConverter/Helpers.cs, Application/FileConverter/Properties/AssemblyInfo.cs, Application/FileConverter/Properties/Resources.pt.resx, Application/FileConverter/Settings.Migration.cs, Application/FileConverter/Settings.Settings.cs, Application/FileConverter/Settings.default.xml, Application/FileConverter/Upgrade/Helpers.cs, Application/FileConverter/ValueConverters/Generic/StringToValueType.cs, Application/FileConverter/Windows/SettingsWindow.xaml, Application/FileConverter/Windows/SettingsWindow.xaml.cs, CHANGELOG.md, Installer/Product.wxs, README.md, version (x86).xml, version.xml
**Change Log**
- Added: Portuguese translation (thanks to Khidreal).
- Fixed: Issue where scale was corrupted when switching application language (github issue #5).
- Fixed: Issue where file metadata were not copied when converting to aac format (github issue #15).
- Tech: Update to ffmpeg 3.2.2 version.
- Tech: Improve security using https instead of http for upgrade system and links (thanks to TheAresjej).
=> File Converter release v1.2.2 

Application/FileConverter/ConversionJobs/ConversionJob_FFMPEG.Converters.cs
Issue #34 
On ffmpeg h264 conversion added video format YUB 420 chroma subsampling
=> On ffmpeg h264 conversion added video format YUB 420 chroma subsampling

Application/FileConverter/ConversionJobs/ConversionJob.cs
Issue #33 
Change output files timestamp to match original file
=> Change output files timestamp to match original file

Application/FileConverter/ConversionJobs/ConversionJob.cs, Application/FileConverter/ConversionJobs/ConversionJob_FFMPEG.Converters.cs, Application/FileConverter/ConversionJobs/ConversionJob_FFMPEG.cs, Application/FileConverter/ConversionPreset/ConversionPreset.cs, Application/FileConverter/FileConverter.csproj, Application/FileConverter/Helpers.cs, Application/FileConverter/ValueConverters/ConversionJobsToProgressState.cs, Application/FileConverter/ValueConverters/ConversionJobsToProgressValue.cs, Application/FileConverter/Windows/MainWindow.xaml, Application/FileConverter/Windows/MainWindow.xaml.cs, FileConverter.sln.DotSettings
Display conversion jobs progress in the Windows taskbar icon.
=> Progress feedback on taskbar icon

Installer/Installer.wixproj, Installer/Product.wxs
…fore allowing to install File Converter.
=> Check for dotnet version in installer

Application/FileConverter/Properties/Resources.de.resx
Resolve conflict of pull request #145 .
=> German Localization resx

Application/FileConverter/Properties/Resources.fr-FR.resx
Correction of some translation errors
=> Update and rename Resources.fr.resx to Resources.fr-FR.resx

Application/FileConverter/Properties/Resources.zh-CN.resx
Add Simplified Chinese Localization.
=> Add Simplified Chinese Localization.

Application/FileConverter/Properties/Resources.tr-TR.resx
Turkish localization for FileConverter.
Translated all data values in Resources.resx into Turkish as Resources.tr-TR.resx
=> FileConverter Turkish language.

Application/FileConverter/ConversionJobs/ConversionJob_Word.cs
Add the bookmarks in pdf when converting from word file.
=> Add the bookmarks in pdf when converting from word file.

Application/FileConverter/FileConverter.csproj, Application/FileConverter/Properties/Resources.el-GR.resx
Many thanks for this wonderful app!
=> Create Resources.el-GR.resx for Greek translation.

Application/FileConverter/Properties/Resources.zh-TW.resx
Add Resources.zh-TW.resx (Make this program support Traditional Chinese)
=> Make this program support Traditional Chinese

Application/FileConverter/Properties/Resources.pt-PT.resx
Update/fix/improve  Portuguese (Portugal) translation
=> Update pt-PT translation

Application/FileConverter/Properties/Resources.he-IL.resx
thanks on your greate software.
this Hebrew translation.
=> Hebrew translation

Application/FileConverter/Application.xaml.cs, Application/FileConverter/FileConverter.csproj, Application/FileConverter/Properties/Resources.he-IL.resx, Application/FileConverter/Properties/Resources.ru-RU.resx, Application/FileConverter/Properties/Resources.zh-CN.resx, Application/FileConverter/Properties/Resources.zh-TW.resx, Application/FileConverter/Settings.default.xml, CHANGELOG.md, Installer/Installer.wixproj, Installer/Product.wxs
- New: Hebrew translation (thanks to AshiVered).
- Fixes: Issue where installer was not working due to registry key not updated correctly during install (issue #382).
- Fixes: Update chinese translations (thanks to jie65535).
- Fixes: Issue where tempo/pitch conversion settings were not considered as default settings resulting is some issues during backward compatibility check.
=> File Converter release v2.0.2

Application/FileConverter/Properties/Resources.fa-IR.resx
Hello.
I have crated Persian Language file.
hope you like it.
=> Persian Translation

Application/FileConverter/Properties/Resources.pt-PT.resx
For commit: https://github.com/Tichau/FileConverter/commit/eb2d6a7468b3ece34dd77688d782ec11b6278d9a
=> Update Portuguese (Portugal) translation

Application/FileConverter/Properties/Resources.sr-Cyrl.resx, Application/FileConverter/Properties/Resources.sr-Latn.resx
Translated File Converter to **Serbian** language (With both **Cyrillic** and **Latin** script).
=> Serbian Cyrillic and Serbian Latin translations

Application/FileConverter/Properties/Resources.ja-jp.resx
Japanese language files have been created.Please add.
=> Add Japanese language file

Application/FileConverter/Properties/Resources.ko-KR.resx, Application/FileConverter/Properties/Resources.resx
=> Add Korean translation

Application/FileConverter/Properties/Resources.vi-VN.resx
Created Vietnamese resource file
=> Add Vietnamese translation

Application/FileConverter/Properties/Resources.ru.resx
This PR adds Russian localization to File Converter.
- Added `Resources.ru.resx` with Russian translations for UI elements
- Translated all main interface elements
- Translated error messages and system notifications
- Translated file type descriptions
- Translations have been proofread for accuracy and natural language flow
- Special characters are properly encoded
- All string resources from base file are covered
None
The translation aims to maintain a balance between technical accuracy and natural Russian language usage. Some technical terms (like "preset") are transliterated rather than translated when that's the common practice in Russian software interfaces.
=> Add Russian localization

Application/FileConverter/Properties/Resources.zh-TW.resx
Some can be improved, and some machine-translated and Simplified Chinese converted terms should be fixed ;)
=> Improve zh-TW Traditional Chinese translation
